//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.1
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PlaceMint.Manager.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("PlaceMint.Manager.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application settings file was not found, so the default values were used..
        /// </summary>
        internal static string appSettingsFileNotFound {
            get {
                return ResourceManager.GetString("appSettingsFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No window groups were created because the windows group configuration file was not found.
        ///If this is the first time running PlaceMint, go to Tools &gt; Configure to setup your first configuration..
        /// </summary>
        internal static string configFileNotFound {
            get {
                return ResourceManager.GetString("configFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DestroyWindow failed with code {0}..
        /// </summary>
        internal static string destroyWindowFailureFormat {
            get {
                return ResourceManager.GetString("destroyWindowFailureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Slot is empty cannot access hWND..
        /// </summary>
        internal static string emptyHWND {
            get {
                return ResourceManager.GetString("emptyHWND", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EnumDesktopWindows failed with code {0}..
        /// </summary>
        internal static string enumDesktopWindowsFailureFormat {
            get {
                return ResourceManager.GetString("enumDesktopWindowsFailureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot set a hWND to {0}. When trying to make a slot with a window, use the constructor without a hWND paramater..
        /// </summary>
        internal static string illegalEmptySlotInitializationFormat {
            get {
                return ResourceManager.GetString("illegalEmptySlotInitializationFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The configuration only has {0} groups, attempted to access group number {1}..
        /// </summary>
        internal static string illegalGroupsIndex {
            get {
                return ResourceManager.GetString("illegalGroupsIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The slot only has {0} window, attempted to access window number {1}..
        /// </summary>
        internal static string illegalHWNDIndex {
            get {
                return ResourceManager.GetString("illegalHWNDIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The window group only has {0} slots, attempted to access slot number {1}..
        /// </summary>
        internal static string illegalSlotIndex {
            get {
                return ResourceManager.GetString("illegalSlotIndex", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The match string for &quot;{0}&quot; is an invalid Regular Expression..
        /// </summary>
        internal static string invalidRegexExceptionFormat {
            get {
                return ResourceManager.GetString("invalidRegexExceptionFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was an invalid value on line {0}..
        /// </summary>
        internal static string InvalidXmlValueFormat {
            get {
                return ResourceManager.GetString("InvalidXmlValueFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pm_log.txt.
        /// </summary>
        internal static string logFileName {
            get {
                return ResourceManager.GetString("logFileName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}-{1}: {2}.
        /// </summary>
        internal static string logFormat {
            get {
                return ResourceManager.GetString("logFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The supplied file path was too long..
        /// </summary>
        internal static string pathTooLong {
            get {
                return ResourceManager.GetString("pathTooLong", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of regular expressions could not be found. To create one use the &quot;Edit Regex List&quot; option..
        /// </summary>
        internal static string regexListFileNotFound {
            get {
                return ResourceManager.GetString("regexListFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SetWindowPos failed to {0} the window: {1}.
        /// </summary>
        internal static string setWindowPosFailureFormat {
            get {
                return ResourceManager.GetString("setWindowPosFailureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowWindow failed to {0} the window: {1}.
        /// </summary>
        internal static string showWindowFailureFormat {
            get {
                return ResourceManager.GetString("showWindowFailureFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A list of slot templates could not be found..
        /// </summary>
        internal static string slotTemplateDileNotFound {
            get {
                return ResourceManager.GetString("slotTemplateDileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt to read xml file that was incorrectly formated..
        /// </summary>
        internal static string wrongXmlFormat {
            get {
                return ResourceManager.GetString("wrongXmlFormat", resourceCulture);
            }
        }
    }
}
